# Generated by Django 3.2.4 on 2021-07-14 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 15, 3, 47, 910878), editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 15, 3, 47, 911459), editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 15, 3, 47, 924085), editable=False),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 15, 3, 47, 923333), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 15, 3, 47, 910267), editable=False),
        ),
    ]
