# Generated by Django 3.2.4 on 2021-07-11 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_auto_20210711_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
