# Generated by Django 3.2.4 on 2021-07-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_postcomment_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.postcomment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.postlikes'),
            preserve_default=False,
        ),
    ]
