# Generated by Django 3.2.4 on 2021-07-11 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20210711_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
