# Generated by Django 3.2.4 on 2021-07-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20210711_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.postcomment'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.postlikes'),
        ),
    ]
