# Generated by Django 3.2.4 on 2021-07-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20210712_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'ordering': ['-id']},
        ),
    ]
