# Generated by Django 3.2.4 on 2021-07-12 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_imagepost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
