# Generated by Django 3.2.4 on 2021-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_imagepost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
