# Generated by Django 3.2.4 on 2021-07-12 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_imagepost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 12, 17, 45, 18, 921810)),
        ),
    ]
