# Generated by Django 3.2.4 on 2021-07-12 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_imagepost_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 18, 59, 35, 838867), editable=False),
        ),
        migrations.AddField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 18, 59, 35, 839328), editable=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 18, 59, 35, 841066), editable=False),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 18, 59, 35, 840534), editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 18, 59, 35, 839922), editable=False),
        ),
    ]
