# Generated by Django 3.2.4 on 2021-07-12 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20210712_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='likes',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.imagepost'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.imagepost'),
        ),
        migrations.AlterField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 19, 30, 4, 864577), editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 19, 30, 4, 865091), editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 19, 30, 4, 873645), editable=False),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 19, 30, 4, 872899), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 19, 30, 4, 865687), editable=False),
        ),
    ]
