# Generated by Django 3.2.4 on 2021-07-13 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20210713_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 18, 8, 348675), editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 18, 8, 349301), editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 18, 8, 356912), editable=False),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 18, 8, 356153), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 18, 8, 348065), editable=False),
        ),
    ]
