# Generated by Django 3.2.4 on 2021-07-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20210713_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 23, 27, 831718), editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 23, 27, 832297), editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 23, 27, 840083), editable=False),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 23, 27, 839350), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 3, 23, 27, 831112), editable=False),
        ),
    ]
