# Generated by Django 3.2.4 on 2021-07-13 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20210713_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followchain',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 5, 14, 35, 436311), editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 5, 14, 35, 436995), editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 5, 14, 35, 445095), editable=False),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 5, 14, 35, 444280), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='No profile for this user, You cannot follow', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 5, 14, 35, 435680), editable=False),
        ),
    ]
