# Generated by Django 3.2.4 on 2021-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0025_auto_20210713_0514'),
        ('gallery', '0025_auto_20210713_0734'),
    ]

    operations = [
    ]
